version: "3.8"
services:
  fastapi:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    entrypoint: /code/entrypoint.sh
#    env_file:
#      - .env

  db:
      image: postgres:13.3
      environment:
        POSTGRES_DB: "db"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"
      ports:
        - "5432:5432"
